### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by arehman26** [dilawar/eye-blink-detector#2]
I am trying to use your code for raspberry pi but i am getting stuck in importing the files itself,
i cant import the extract and webcam file in the blink.py, i have tried whatever i could find

**Comment by dilawar** [comment]
Unfortunately I don't have raspberry-pi to test the code. If you can post the
exact error msg, I can give some pointers.

**Comment by arehman26** [comment]
I got the file import to work but when I try to run the code I get this error.

usage: blinky.py [-h] -- video-file VIDEO_FILE [--bbox BBOX [BBOX...]]
blinky.py: error: argument --video-file/-f is required

Do we have to record a video for it to work or does it capture the video and than look for blinks at the same time?

You have specified two methods for this process, one is edge and the other is dark pixals. both of them are integrated into all together or are they like 2 files for one method?

Thanks

**Comment by dilawar** [comment]
Ah, I see. Currently the code works for video files only. I am making changes to
make it work on both camera and video file. I hope to finish/test it by this
weekend. 

Both methods run currently. There is no way to choose one between them. I'll
probably make it optional to choose one.

## 

best,
    Dilawar

**Comment by dilawar** [comment]
There is another script `~/blinky_webcam.py` which might be able to use webcam (it works on linux). You would need to do the following on ubuntu
- apt install gnuplot
- pip install gnuplotlib

**Comment by vasulg** [comment]
getting this error working on ubuntu
Traceback (most recent call last):
  File "/home/vasupilli/Desktop/New folder (3)/Current/eye-blink-detector-master/blinky_webcam.py", line 176, in <module>
    main()
  File "/home/vasupilli/Desktop/New folder (3)/Current/eye-blink-detector-master/blinky_webcam.py", line 153, in main
    init()
  File "/home/vasupilli/Desktop/New folder (3)/Current/eye-blink-detector-master/blinky_webcam.py", line 76, in init
    box_ = webcam.get_bounding_box(fstFrame)
  File "/home/vasupilli/Desktop/New folder (3)/Current/eye-blink-detector-master/webcam.py", line 143, in get_bounding_box
    current_frame_ = frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by dilawar** [comment]
Seems like that webcam is not being detected by opencv. 

Can you see your webcam feed in some other app like cheese?

⁣Sent from BlueMail ​

**Comment by vasulg** [comment]
thanks a lot.. that got rectified. Now another error confronting me ..
Traceback (most recent call last):
  File "/home/vasupilli/Desktop/blinky_webcam.py", line 176, in <module>
    main()
  File "/home/vasupilli/Desktop/blinky_webcam.py", line 153, in main
    init()
  File "/home/vasupilli/Desktop/blinky_webcam.py", line 76, in init
    box_ = webcam.get_bounding_box(fstFrame)
AttributeError: 'module' object has no attribute 'get_bounding_box


I tried pip install planar  module.. but I ended up with error.. Not
getting installed.
Please send a solution for this
thanks in advance!

**Comment by dilawar** [comment]
Check if recent commit fixed your issue.

**Comment by dilawar** [comment]
No activity.
