### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by dberma15** [dilawar/eye-blink-detector#4]
I'm not really sure I understand the output. Could you explain the two files that are output, what the columns mean, what the units are, etc.

I received two output files for a 30 second video but the "# time" column in one file goes up to 8 seconds and the "# time" column in the other only goes up to 12 and has 291 rows. Can you explain this?

**Comment by dilawar** [comment]
Both algorithms computes every time N and M entries have been added to their input timeseries. When the process terminates, last N and M entries are not written to result file. For examples, if your video was 300 seconds long, files will contain (300-24) seconds and (300-18) seconds - given that fps does not change. 

I'll leave this issue open to be fixed later.

**Comment by dberma15** [comment]
I'm sorry but I'm a bit confused by this. What are N and M? Where did you get 24 and 18 from? The webm video I made is a looped video where the person blinks twice two seconds in, then nothing for six seconds, 2 blinks, nothing for six seconds, etc. Why are these the results? Here is a gif of the video I'm using https://gfycat.com/LightheartedSolidAfricanwilddog

[eyetracker_test.webm_out.xlsx](https://github.com/dilawar/eye-blink-detector/files/841270/eyetracker_test.webm_out.xlsx)
[eyetracker_test.webm_blinks_using_edges.xlsx](https://github.com/dilawar/eye-blink-detector/files/841272/eyetracker_test.webm_blinks_using_edges.xlsx)

**Comment by dilawar** [comment]
Thanks for the data. I'll test it. N and M were just placeholders, I forgot how long the time series had to be.



⁣Sent from BlueMail ​

**Comment by dberma15** [comment]
What I'd like to get out of this tool is a csv with a list of times into the video indicating when a blink occured. Is this capable of doing that? 


I just realized something that might be an insight to the problem. I get the following error:
```

Traceback (most recent call last):
    File "blinky.py", line 61, in <module>
        main(vars(args))
    File "blinky.py", line 35, in main
        pixalBlinks = extract.find_blinks_using_pixals(data)
    File "C:\Users\bermads1\Documents\SCITE\blink\extract.py", line 140, in find_blinks_using _pixals
        bT, yy = t[x-1:-x], w[x-1:-x] - smoothW
ValueError: operands could not be broadcast together with shapes (0,) (75,)
```

I'm not sure what I did wrong. the webm file was saved in the same directory as blinky.py as eyetracker_test.webm and the command I run is:
`python blinky.py -f eyetracker_test.webm`

**Comment by dilawar** [comment]
I tested the your video. Seems like opencv is having trouble converting it to grayscale after first few frames. 

     $ ./blinky.py -f ~/Download/issue4.webm

Unfortunately I am short of time these days to test/reply quickly as I wish. Moreover, we are now moving this demo project into a real time system (with lab-rats); so most of the bugs is likely to be fixed in upcoming month.

**Comment by dilawar** [comment]
No activity.
